### ISSUE TITLE
Cannot build 32-bit Windows target

### ISSUE THREAD

**Issue by WilfredC64** [ir1keren/rs-drivelist#1]
In the Cargo.toml the target for Windows is specific set for 64-bit using msvc compiler:

[target.x86_64-pc-windows-msvc.dependencies]

Therefore it cannot be compiled for 32 bit targets like i686-pc-windows-msvc.

To solve this, please use the following instead:

[target.'cfg(windows)'.dependencies]

**Comment by ir1keren** [comment]
All Windows flavors and all linux flavors has been added
